### ISSUE TITLE
Change data-storage structure

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#170]
Since we are changing the messages structure, and will soon be using a hierarchical data-saving options, we have decided to change our entire database ( 🎉 )

All information will now be saved in this brand new hierarchical (tree-like) structure. Therefore, some changes are bound to be made.

This issue will be closed after achieving the next goals:

- [x] `ServerManager` class will be changed ( #134 )
- [x] `DatabaseManager` class will be implemented (#134)
- [x]  `system.user_information` package will be changed / replaced to match the new design
- [x] `SystemCore` will be implementing the `Savable` interface in a way which will allow using it's functionalities in order to save the system's state on the server ( also relevant to #136)

**Comment by inbalzukerman** [comment]
All changes required were implemented, some were decided upon as unnecessary, and therefore this issue can be cloded
